"""publicpubs

Revision ID: b402b32fed99
Revises: 
Create Date: 2020-02-24 09:37:41.782100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b402b32fed99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('key_psc_author', sa.String(length=128), nullable=True),
    sa.Column('abstact', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_publications')
    # ### end Alembic commands ###
